---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  vars:
    - user: remote_user
    - home: /home/remote_user   
    - workspace: ''
    - build: ''
    - document_root: '/document_root'
  tasks:
    - name: utente e home corrente
      debug:
        msg: "Username: {{ user }}, Home dir: {{ home }}"
    
    # - name: Check if file already exists
    #   command: ls /home/{{ user }}/myfile
    #   register: file_exists
    #   ignore_errors: yes

    # - name: create file for user
    #   copy:
    #     dest: "/home/{{ user }}/myfile"
    #     content: |
    #       line 01
    #       line 02
    #   when: file_exists is failed

    # - name: show message if file exists
    #   debug:
    #     msg: The user file already exists.
    #   when: file_exists is succeeded

    # - name: Create a bz2 archive of a globbed path, while excluding specific dirnames
    #   community.general.archive:
    #     path:
    #     - /app*
    #     dest:  /home/{{ user }}/app.tar.bz2
    #     exclude_path:
    #     - /app/.DS_Store
    #     - /app/.laminas-ci
    #     format: bz2
    
    # - name: Check if zip already exists
    #   command: ls /home/{{ user }}/app.tar.bz2
    #   register: file_tar_exists
    #   ignore_errors: yes

    - name: Check Directory Deployment Exite
        stat:
          path: /ZendPhp/Deployment
        register: register_name

    - name: Create Diretory /ZendPhp/Deployment
      file:
        path: /ZendPhp/Deployment
        state: directory
        mode: 755
        owner: zendphp
        group: zendphp
      when: not register_name.stat.exists

    - name: Check if zip already exists
      command: ls /tmp/app.zip 
      register: file_exists
      ignore_errors: yes

    - name: Copy build on remote server
      ansible.builtin.file:
        path: /tmp/app.zip
        state: absent
      when: file_exists is succeeded

    - name: Copy build on remote server
      ansible.builtin.copy:
        src:  "{{ workspace }}/app.zip"
        dest: /tmp/app.zip 

    - name: Check if folder app already exists
      command: rm -fr "/app_{{ build }}"
      ignore_errors: yes
         

    - name: Creates Directory
      ansible.builtin.file:
        # path: "{{ home }}/app_{{ build }}"
        path: "/app_{{ build }}"
        state: directory
        mode: 777
        owner: zendphp
        group: zendphp

    # - name: Check if zip already exists
    #   command: mkdir "/app_{{ build }}"
    #   ignore_errors: yes
     

    - name: Extract app.zip into /app
      ansible.builtin.unarchive:
        src : "/tmp/app.zip" 
        dest: "/app_{{ build }}"
        owner: zendphp
        group: zendphp
        remote_src: yes
        
    - name: Create symbolic link to virtualhost
      file:
        src: "/app_{{ build }}"
        dest: "{{document_root}}"
        owner: zendphp
        group: zendphp
        state: link     