---
- hosts: [dev1,dev2,dev3]
  become: yes
  become_method: sudo
  gather_facts: yes
  vars:
    - user: remote_user
    - home: /home/remote_user   
    - workspace: ''
    - build: ''
    - document_root: '/document_root'
  tasks:
    - name: utente e home corrente
      debug:
        msg: "Username: {{ user }}, Home dir: {{ home }}"
    
    # - name: Check if file already exists
    #   command: ls /home/{{ user }}/myfile
    #   register: file_exists
    #   ignore_errors: yes

    # - name: create file for user
    #   copy:
    #     dest: "/home/{{ user }}/myfile"
    #     content: |
    #       line 01
    #       line 02
    #   when: file_exists is failed

    # - name: show message if file exists
    #   debug:
    #     msg: The user file already exists.
    #   when: file_exists is succeeded

    # - name: Create a bz2 archive of a globbed path, while excluding specific dirnames
    #   community.general.archive:
    #     path:
    #     - /app*
    #     dest:  /home/{{ user }}/app.tar.bz2
    #     exclude_path:
    #     - /app/.DS_Store
    #     - /app/.laminas-ci
    #     format: bz2
    
    # - name: Check if zip already exists
    #   command: ls /home/{{ user }}/app.tar.bz2
    #   register: file_tar_exists
    #   ignore_errors: yes

    - name: Ansible check directory.
      stat:
        path: /ZendPhp/Deployment
      register: my_folder
    
    - name: "echo if directory already existed"
      debug:
        msg: "the jboss directory is already existed"
      when: my_folder.stat.exists  

    - name: "Ansible Create directory if not exists"
      file:
        path: /ZendPhp/Deployment
        state: directory
        mode: 0755
        group: root
        owner: root
      when: my_folder.stat.exists == false 

    - name: Check if zip already exists
      command: ls /tmp/app.zip 
      register: file_exists
      ignore_errors: yes

    - name: Copy build on remote server
      ansible.builtin.file:
        path: /tmp/app.zip
        state: absent
      when: file_exists is succeeded

    - name: Copy build on remote server
      ansible.builtin.copy:
        src:  "{{ workspace }}/app.zip"
        dest: /tmp/app.zip 

    - name: Check if folder app already exists
      command: rm -fr "/app_{{ build }}"
      ignore_errors: yes
         

    - name: Creates Directory
      ansible.builtin.file:
        # path: "{{ home }}/app_{{ build }}"
        path: "/ZendPhp/Deployment/app_{{ build }}"
        state: directory
        mode: 777
        owner: zendphp
        group: zendphp

    # - name: Check if zip already exists
    #   command: mkdir "/app_{{ build }}"
    #   ignore_errors: yes
     

    - name: Extract app.zip into /app
      ansible.builtin.unarchive:
        src : "/tmp/app.zip" 
        dest: "/ZendPhp/Deployment/app_{{ build }}"
        owner: zendphp
        group: zendphp
        remote_src: yes
        
    - name: Create symbolic link to virtualhost
      file:
        src: "/ZendPhp/Deployment/app_{{ build }}"
        dest: "{{document_root}}"
        owner: zendphp
        group: zendphp
        state: link  
  # handlers:
  #   - name: Check HTTP Service Nginx
  #     uri:
  #       url:http://{{ansible_default_ipv4.address}}
  #       status_code: 200

- hosts: [dev4]
  become: yes
  gather_facts: yes
  vars:
    - user: remote_user
    - home: /home/remote_user   
    - php_version: 7.4
    - app_url: pink.pinkinvestment.tz
    - ioncube_archive_url: https://downloads.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz
  tasks:
    - name: utente e home corrente
      debug:
        msg: "Username: {{ user }}, Home dir: {{ home }}"

    - name: Installing Nginx to the host(s)
      apt:
        name: nginx
        state: present    
...   